#!/usr/bin/env bash

# This script display To infinity and beyond indefinitely With a sleep 2 in between each iterationI am invincible!!! when receiving a SIGTERM signa

trap interrup SIGTERM



interrup()

{

    echo "I am invincible!!!"

}



while true

do

    echo "To infinity and beyond"

    sleep 2

done
